version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/yumemi
    command: sh -c "cd yumemi && npm run dev"
    ports:
        - "3000:3000"